version: '3.8'

services:
  plex-mapper:
    build: .
    container_name: plex-jellyfin-mapper
    ports:
      - "5000:5000"
    volumes:
      # This saves their database to a folder called "data" next to the compose file
      - ./data:/data
    environment:
      # Users will put THEIR keys here when they download your app
      - APP_USERNAME=admin
      - APP_PASSWORD=password123
      - PLEX_URL=http://192.168.2.203:32400
      - PLEX_TOKEN=xxxxxxxxxxxxxxxxxxxxxxx
      - PLEX_LIBRARY_NAME=TV
      - JELLYFIN_URL=http://192.168.2.202:8096
      - JELLYFIN_API_KEY=xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
      - JELLYFIN_USER_ID=xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
      - TARGET_LABEL=PLEXLABEL
    restart: unless-stopped
